### ISSUE TITLE
[bug] 斗鱼房间无法解析

### ISSUE THREAD

**Issue by heartnn** [iiijam/ice_live_viewer#16]
https://www.douyu.com/501761

Exception: {error: 742017, msg: 后端服务异常, data: }
#0      Douyu._getRoomStreamInfo (package:ice_live_viewer/utils/http/douyuparser.dart:37)
<asynchronous suspension>
#1      Douyu._getRoomUrl (package:ice_live_viewer/utils/http/douyuparser.dart:80)
<asynchronous suspension>
#2      Douyu.getRoomFullInfo (package:ice_live_viewer/utils/http/douyuparser.dart:124)
<asynchronous suspension>
#3      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628)
<asynchronous suspension>

**Comment by heartnn** [comment]
![Screenshot_2022-12-14-14-30-15-14_10e5e160bf60cc6c2f5f298e18629f55](https://user-images.githubusercontent.com/457514/207523138-4d675a6c-767f-43e5-a910-45ef5ae54ae2.jpg)

补充一张图片，可以看到头像和信息是无法获得的
